Repository Goorm-OGJG/Da-It-Gym-FE, pull requests merged in 2023-11, with the labels that each got.

#28 Feat : DIG-46 FE 피드 미리보기 오버레이 추가
  src/components/FeedPreview/FeedPreview.style.tsx
  src/components/FeedPreview/FeedPreview.tsx
Labels: enhancement

#32 Fix : App.style.tsx 디자인 깨짐 수정
  src/App.style.tsx
Labels: bug

#30 Design : DIG-50 FE 운동일지 관련 UI 수정
  src/components/ExerciseSetComponent/ExerciseSetComponent.tsx
  src/hooks/useRestTimer.tsx
  src/pages/ExerciseDiary/components/ExerciseDiaryDefault/ExerciseDiaryDefault.tsx
  src/pages/ExerciseDiary/components/ExerciseDiarySuccess/ExerciseDiarySuccess.tsx
  src/pages/ExerciseDiary/components/ExerciseNav/ExerciseNav.tsx
Labels: enhancement

#31 Feat : DIG-51 FE 피드 미리보기 수정사항 반영
  src/components/FeedPreview/FeedPreview.style.tsx
  src/components/FeedPreview/FeedPreview.tsx
Labels: enhancement

#33 Feat : DIG-53 FE 회원가입 닉네임 설정 UI 및 useDebounce
  src/App.tsx
  src/components/Input/Input.tsx
  src/hooks/useDebounce.tsx
  src/pages/Signup/Signup.style.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/components/SignupButton.style.tsx
  src/pages/Signup/components/SignupButton.tsx
  src/pages/Signup/components/SignupInput.style.tsx
  src/pages/Signup/components/SignupInput.tsx
  src/pages/Signup/components/SignupTitle.style.tsx
  src/pages/Signup/components/SignupTitle.tsx
Labels: enhancement

#37 Feat : DIG-59 공통 컴포넌트 UI 수정
  src/components/RoutineUser/RoutineUser.style.tsx
  src/components/RoutineUser/RoutineUser.tsx
  src/components/SideMenu/SideMenu.tsx
Labels: enhancement

#42 Feat : DIG-68 배포 파일 작성
  Dockerfile
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/service.yaml
Labels: enhancement

#43 Fix : DIG-69 deployment.yaml 이미지 주소 변경
  k8s/deployment.yaml
Labels: bug

#41 Fix : DIG-61 FE My페이지 이름 -> Profile 페이지로 변경
  src/App.tsx
  src/api/useProfileAPI.tsx
  src/components/Nav/Nav.tsx
  src/components/SideMenu/SideMenu.tsx
  src/pages/MyPage/components/Diaries/Diaries.tsx
  src/pages/Profile/Profile.style.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/components/Bookmark/Bookmark.style.tsx
  src/pages/Profile/components/Bookmark/Bookmark.tsx
  src/pages/Profile/components/Diaries/Diaries.style.tsx
  src/pages/Profile/components/Diaries/Diaries.tsx
  src/pages/Profile/components/FollowModal/FollowModal.style.tsx
  src/pages/Profile/components/FollowModal/FollowModal.tsx
  src/pages/Profile/components/Inbody/Inbody.style.tsx
  src/pages/Profile/components/Inbody/Inbody.tsx
  src/pages/Profile/components/InbodyModal/InbodyModal.style.tsx
  src/pages/Profile/components/InbodyModal/InbodyModal.tsx
  src/pages/Profile/components/Routines/Routines.style.tsx
  src/pages/Profile/components/Routines/Routines.tsx
  src/pages/Profile/components/UserContent/UserContent.style.tsx
  src/pages/Profile/components/UserContent/UserContent.tsx
  src/pages/Profile/components/UserProfile/UserProfile.style.tsx
  src/pages/Profile/components/UserProfile/UserProfile.tsx
Labels: bug

#40 Feat : DIG-63 루틴 관련 API 틀 작업
  src/api/useRoutineAPI.tsx
Labels: enhancement

#39 Fix : DIG-62 루틴 상세보기, 루틴 작성 페이지 디자인 버그 해결
  src/pages/FeedNewRoutine/FeedNewRoutine.style.tsx
  src/pages/FeedRoutine/FeedRoutine.tsx
Labels: bug

#45 Feat : DIG-80 라우터 설정 및 로그인시 Outlet 설정
  src/App.tsx
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
  src/pages/Login/LoginLayout.tsx
Labels: enhancement

#46 Feat : DIG-80 라우터 설정, Outlet 설정
  src/App.tsx
  src/components/PrivateRoute.tsx
Labels: enhancement

#38 Feat : DIG-55 FE 관리자 회원 조회 페이지 UI
  src/App.tsx
  src/components/UserDetailModal/UserDetailModal.style.tsx
  src/components/UserDetailModal/UserDetailModal.tsx
  src/pages/Admin/Admin.style.tsx
  src/pages/Admin/Admin.tsx
  src/pages/Admin/AdminTeble/AdminTeble.style.tsx
  src/pages/Admin/AdminTeble/AdminTeble.tsx
Labels: enhancement

#49 Fix : DIG-96 회원가입 페이지 닉네임 로직 수정
  src/hooks/useDebounce.tsx
  src/pages/Signup/components/SignupButton.tsx
  src/pages/Signup/components/SignupInput.style.tsx
  src/pages/Signup/components/SignupInput.tsx
Labels: enhancement

#50 Feat : DIG-102 로그인 로딩 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/Login/components/KakaoLogin.tsx
  src/pages/Login/components/KakaoSignUp.style.tsx
  src/pages/Login/components/KakaoSignUp.tsx
  src/pages/LoginLoading/LoginLoading.style.tsx
  src/pages/LoginLoading/LoginLoading.tsx
Labels: enhancement

#51 Feat : DIG-104 FE 카카오 로그인, 로그아웃 API
  src/api/useAxios.tsx
  src/api/useUserAPI.tsx
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
  src/components/SideMenu/SideMenu.tsx
Labels: enhancement

#52 Feat : DIG-106 회원 복구 페이지 UI 구현 및 회원가입 페이지 수정
  src/api/useUserAPI.tsx
  src/pages/Recovery/Recovery.style.tsx
  src/pages/Recovery/Recovery.tsx
  src/pages/Recovery/components/RecoveryButton.style.tsx
  src/pages/Recovery/components/RecoveryButton.tsx
  src/pages/Recovery/components/RecoveryTitle.style.tsx
  src/pages/Recovery/components/RecoveryTitle.tsx
  src/pages/Signup/components/SignupButton.tsx
  src/pages/Signup/components/SignupInput.style.tsx
  src/pages/Signup/components/SignupInput.tsx
  src/recoil/signupState.ts
Labels: enhancement

#53 Feat : DIG-109 회원가입 페이지 수정 및 내 정보 localSotrage에 저장
  src/App.tsx
  src/api/useUserAPI.tsx
  src/main.tsx
  src/pages/Signup/components/SignupButton.tsx
  src/pages/Signup/components/SignupInput.tsx
  src/recoil/userInfoState.ts
Labels: enhancement

#55 Feat : DIG-118 API 함수 작성 및 기능 적용
  package-lock.json
  package.json
  src/App.tsx
  src/api/useChatAPI.tsx
  src/api/useRoutineAPI.tsx
  src/components/ExerciseAccordion/AddExerciseModal.tsx
  src/components/ExerciseCard/ExerciseCard.tsx
  src/components/ExercisePartLabel/ExercisePartLabel.tsx
  src/components/FeedInteractionInfo/FeedInteractionInfo.tsx
  src/components/RoutineUser/RoutineUser.style.tsx
  src/components/RoutineUser/RoutineUser.tsx
  src/constants/excercise.ts
  src/hooks/useCounts.tsx
  src/hooks/useExercise.tsx
  src/hooks/useRoutine.tsx
  src/hooks/useRoutineDetailState.tsx
  src/pages/Chat/Chat.tsx
  src/pages/ChatRooms/ChatRooms.tsx
  src/pages/FeedNewRoutine/FeedNewRoutine.style.tsx
  src/pages/FeedNewRoutine/FeedNewRoutine.tsx
  src/pages/FeedRoutine/FeedRoutine.tsx
  src/pages/FeedRoutineDetail/FeedRoutineDetail.styled.tsx
  src/pages/FeedRoutineDetail/FeedRoutineDetail.tsx
Labels: enhancement

#58 Fix : DIG-124 유저정보 API 수정
  src/api/useUserAPI.tsx
  src/constants/regExp.ts
  src/pages/Signup/components/SignupInput.tsx
Labels: enhancement

#59 Feat : DIG-127 루틴 상세보기 페이지 스크랩 기능 구현
  src/components/RoutineAccordion/RoutineAccordion.style.tsx
  src/components/RoutineAccordion/RoutineAccordion.tsx
  src/pages/FeedNewRoutine/FeedNewRoutine.tsx
  src/pages/FeedRoutineDetail/FeedRoutineDetail.styled.tsx
  src/pages/FeedRoutineDetail/FeedRoutineDetail.tsx
Labels: enhancement

#61 Feat : DIG-133 운동일지 피드 API 작업
  public/images/noData.png
  src/api/useFeedDiaryAPI.tsx
  src/components/FeedEmptyDataUI/FeedDiaryEmpty.style.tsx
  src/components/FeedEmptyDataUI/FeedDiaryEmpty.tsx
  src/components/Nav/Nav.tsx
  src/components/SideMenu/SideMenu.tsx
  src/pages/FeedDiary/FeedDiary.tsx
  src/pages/FeedDiary/components/FeedDiaryBody.style.tsx
  src/pages/FeedDiary/components/FeedDiaryBody.tsx
  src/pages/FeedDiary/components/SearchTag.tsx
  src/recoil/feedDiaryState.ts
Labels: enhancement

#62 DIG-134 FE 고객센터 UI
  src/pages/CustomerCenter/Board/FAQ.style.tsx
  src/pages/CustomerCenter/Board/FAQItem.tsx
  src/pages/CustomerCenter/CustomerCenter.style.tsx
  src/pages/CustomerCenter/CustomerCenter.tsx
Labels: enhancement

#64 Feat : DIG-141 FE 렌더링 오류 수정
  src/api/useExerciseDiaryAPI.tsx
  src/api/useProfileAPI.tsx
  src/components/ExerciseCalendar/ExerciseCalendar.tsx
  src/pages/ExerciseDiary/ExerciseDiary.tsx
  src/pages/ExerciseDiary/components/ExerciseDiaryDefault/ExerciseDiaryDefault.tsx
  src/pages/ExerciseDiary/components/ExerciseDiarySuccess/ExerciseDiarySuccess.tsx
  src/pages/Profile/components/Diaries/Diaries.style.tsx
  src/pages/Profile/components/Diaries/Diaries.tsx
  src/pages/Profile/components/Routines/Routines.style.tsx
  src/pages/Profile/components/Routines/Routines.tsx
  src/pages/Profile/components/UserProfile/UserProfile.style.tsx
  src/pages/Profile/components/UserProfile/UserProfile.tsx
  src/recoil/exerciseState.ts
Labels: bug

#67 Feat : DIG-149 채팅방 및 채팅방 구현 완료
  index.html
  package-lock.json
  package.json
  src/api/useChatAPI.tsx
  src/api/useChatRoomAPI.tsx
  src/api/useRoutineAPI.tsx
  src/api/useTimeCalculate.tsx
  src/pages/Chat/Chat.style.tsx
  src/pages/Chat/Chat.tsx
  src/pages/Chat/FriendChat.style.tsx
  src/pages/Chat/FriendChat.tsx
  src/pages/Chat/MyChat.style.tsx
  src/pages/Chat/MyChat.tsx
  src/pages/ChatRooms/ChatRoom.style.tsx
  src/pages/ChatRooms/ChatRoom.tsx
  src/pages/ChatRooms/ChatRooms.tsx
  src/pages/Profile/components/UserProfile/UserProfile.tsx
Labels: enhancement

#66 Feat : DIG-145 운동일지 전체보기, 팔로우보기 API 작업
  src/api/useFeedDiaryAPI.tsx
  src/pages/FeedDiary/components/FeedDiaryBody.tsx
  src/pages/FeedDiary/components/FeedDiaryHeader.style.tsx
Labels: enhancement

#72 Fix : DIG-158 FE 공통 컴포넌트 UI, 스타일 수정
  src/components/FeedEmptyDataUI/FeedDiaryEmpty.style.tsx
  src/components/SideMenu/SideMenu.style.tsx
  src/pages/EditProfile/EditProfile.tsx
  src/pages/FeedDiary/FeedDiary.tsx
  src/pages/FeedDiary/components/FeedDiaryBody.style.tsx
  src/pages/FeedDiary/components/FeedDiaryBody.tsx
  src/pages/FeedDiaryShare/FeedDiaryShare.tsx
  src/pages/FeedDiaryShare/components/FDSTag.tsx
  src/pages/FeedRoutine/FeedRoutine.style.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/components/KakaoLogin.style.tsx
  src/pages/LoginLoading/LoginLoading.tsx
  src/pages/Recovery/components/RecoveryTitle.tsx
  src/pages/Signup/components/SignupTitle.tsx
Labels: enhancement

#71 Fix : DIG-157 채팅 AccessToken 만료 시 채팅 안되는 버그 해결
  src/api/useChatAPI.tsx
  src/pages/Chat/Chat.tsx
Labels: bug, enhancement

#74 Fix : DIG-162 피드 일지 수정 작업
  src/pages/FeedDiary/FeedDiary.tsx
Labels: enhancement

#76 Feat : DIG-164 FE 친구추천 페이지
  src/App.tsx
  src/api/useExerciseDiaryAPI.tsx
  src/api/useProfileAPI.tsx
  src/components/FollowUser/FollowUser.style.tsx
  src/pages/EditProfile/components/TrainerEdit/TrainerEdit.tsx
  src/pages/EditProfile/components/UserEdit/UserEdit.tsx
  src/pages/ExerciseDiary/ExerciseDiary.tsx
  src/pages/FeedImport/FeedImport.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/components/InbodyModal/InbodyModal.style.tsx
  src/pages/Profile/components/InbodyModal/InbodyModal.tsx
  src/pages/Profile/components/Routines/Routines.tsx
  src/pages/Profile/components/UserProfile/UserProfile.style.tsx
  src/pages/Profile/components/UserProfile/UserProfile.tsx
  src/pages/UserRecommend/UserRecommend.tsx
Labels: enhancement

#73 Fix : FE Nav 바 자동설정 변경으로 인한 컴포넌트 삭제
  src/pages/Chat/Chat.tsx
  src/pages/ChatRooms/ChatRooms.tsx
  src/pages/FeedRoutine/FeedRoutine.tsx
  src/pages/FeedRoutineDetail/FeedRoutineDetail.tsx
Labels: bug, enhancement

#77 Fix : DIG-167 유저 정보 받아오는 것 수정
  src/api/useUserAPI.tsx
Labels: bug

#78 Feat : DIG-168 FCM 알림 기능 작업
  index.html
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/App.tsx
  src/components/PrivateRoute.tsx
  src/main.tsx
  tsconfig.json
Labels: enhancement

#79 Fix : DIG-169 FE 친구 추천 요청 변수명 수정
  src/api/useProfileAPI.tsx
  src/pages/Profile/components/UserProfile/UserProfile.style.tsx
  src/pages/Profile/components/UserProfile/UserProfile.tsx
  src/pages/UserRecommend/UserRecommend.tsx
Labels: bug

#83 Feat : DIG-174 스크랩 디자인 및 이미지 추가
  public/images/diaryScrap.png
  public/images/routineScrap.png
Labels: enhancement

#82 Fix : DIG-173 FE 로그아웃 요청 수정
  src/components/SideMenu/SideMenu.tsx
  src/pages/UISample/UISample.tsx
Labels: bug

#85 Fix : DIG-176 FE 알림 설정 수정 및 리다이렉트 URL 수정
  src/App.tsx
  src/api/useProfileAPI.tsx
  src/api/useUserAPI.tsx
  src/components/PrivateRoute.tsx
  src/components/SideMenu/SideMenu.tsx
  src/pages/Login/components/KakaoLogin.tsx
Labels: enhancement

#80 DIG-172 FE admin API 로직 추가 및 기능 변경
  src/api/useAdminAPI.tsx
  src/components/UserDetailModal/UserDetailModal.style.tsx
  src/components/UserDetailModal/UserDetailModal.tsx
  src/pages/Admin/Admin.style.tsx
  src/pages/Admin/Admin.tsx
  src/pages/Admin/AdminTeble/AdminTeble.tsx
  src/pages/Admin/component/AdminPagination.style.tsx
  src/pages/Admin/component/AdminPagination.tsx
  src/pages/Admin/component/AdminTable.style.tsx
  src/pages/Admin/component/AdminTable.tsx
  src/pages/CustomerCenter/Board/FAQ.style.tsx
  src/pages/CustomerCenter/Board/FAQItem.tsx
  src/pages/CustomerCenter/CustomerCenter.style.tsx
  src/pages/CustomerCenter/CustomerCenter.tsx
Labels: enhancement

#86 Fix : DIG-180 프로필 편집 및 회원가입 버튼 수정
  src/pages/EditProfile/EditProfile.tsx
  src/pages/FeedDiary/components/FeedDiaryBody.style.tsx
  src/pages/Signup/components/SignupButton.tsx
Labels: bug

#87 Fix : DIG-182 FE 알림 설정 env import 수정
  src/App.style.tsx
  src/App.tsx
Labels: bug
